MusicPlatform/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^userProfile/', include('userProfile.urls')),
]

userProfile/urls.py
from django.conf.urls import url

from . import views

app_name = 'userProfile'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^(?P<albumId>[0-9]+)/$', views.detail, name='detail'),


    url(r'^(?P<albumId>[0-9]+)/favorite/$', views.favorite, name='favorite'),

]

userProfile/models.py
# -*- coding: utf-8 -*-

from django.db import models
# Create your models here.

class User(models.Model):
	userName = models.CharField(max_length=16)
	fullName = models.CharField(max_length=80)
	email = models.CharField(max_length=60)
	password = models.CharField(max_length=32)
	adress = models.CharField(max_length=500)
	phone = models.CharField(max_length=14)
	userPhoto = models.CharField(max_length=1000)
	def __str__(self):
		return self.userName + ' - ' + self.fullName + ' - ' + self.email + ' - ' + self.phone


class Album(models.Model):
	artist = models.CharField(max_length=80)
	albumTitle = models.CharField(max_length=250)
	genre = models.CharField(max_length=40)
	albumLogo = models.CharField(max_length=1000)

	def __str__(self):
	 	return self.albumTitle + ' - ' + self.artist


class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	fileType = models.CharField(max_length=10)
	songTitle = models.CharField(max_length=250)
	isFavorite = models.BooleanField(default=False)

	def __str__(self):
	 	return self.songTitle

userProfile/views.py
# -*- coding: utf-8 -*-
from django.http import Http404
from django.shortcuts import render, get_object_or_404

from .models import Album, Song


# Create your views here.

def index(request):
	allAlbums = Album.objects.all()
	# html = ''
	# for album in allAlbums:
	# 	url = '/userProfile/' + str(album.id) + '/'
	# 	html += '<a href="' + url + '">' + album.albumTitle + '</a><br>'
	context = {
		'allAlbums' : allAlbums,
	}
	return render(request, 'userProfile/index.html', context)


def detail(request, albumId):
	#album = Album.objects.get(pk=albumId)
	album = get_object_or_404(Album, pk=albumId)
	return render(request, 'userProfile/detail.html', {'album' : album})


def favorite(requset, albumId):
    album = get_object_or_404(Album, pk=albumId)
    try:
        selectedSong = album.song_set.get(pk=requset.POST['song'])

    except (KeyError, Song.DoesNotExist):
        return render(requset, 'userProfile/detail.html', {
            'album' : album,
            'error_message' : "You haven't selected a valid song!",
        })
    else:
        selectedSong.isFavorite = True
        selectedSong.save()
        return render(requset, 'userProfile/detail.html', {'album': album})

userProfile/templates/userProfile/detail.html
<img src="{{ album.albumLogo }}">

<h1>{{ album.albumTitle }}</h1>
<h2>{{ album.artist }}</h2>

{#<ul>#}
{##}
{#    {% for song in album.song_set.all %}#}
{#        <li>{{ song.songTitle }} - {{ song.fileType }} - {{ song.album.artist }} </li>#}
{#    {% endfor %}#}
{##}
{#</ul>#}

{%  if error_message  %}
<p> <strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'userProfile:favorite' album.id %}" method="post">
    {% csrf_token %}
        {% for song in album.song_set.all %}
            <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
            <label for="song{{ forloop.counter }}">
                {{ song.songTitle }}
                {%  if song.isFavorite  %}
                    <img src="http://i.imgur.com/b9b13Rd.png" />
                {% endif %}
            </label> <br>
        {% endfor %}
        <input type="submit" name="favorite"  value="Favorite">
</form>

userProfile/templates/userProfile/index.html
{% if allAlbums %}
<h3>Albums :</h3>
	<ul>
		{% for album in allAlbums %}
		<li><a href="{% url 'userProfile:detail' album.id %}"> {{album.albumTitle}}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<h3>Sorry! No albums to show</h3>
{% endif %}